### PR TITLE
Fixing: change a item count with 3 to 5.

### LINKED ISSUE #105: Terrain texture in jungle lvl
Some times terrein texture tile are not show in some places.

### PR DESCRIPTION
**Pull request by IgorekLoschinin**
fix #105 Changing texture mapping to ground.

### CODE REVIEW

File: src/JungleLvl/private/ground.cpp [hunk 1]
```diff
@@ -14,6 +14,6 @@ Ground::Ground() : CRAWL::GroundClaster("JungelGroud") {
 }
 
 unsigned int Ground::itemsCount() const {
-    return 3;
+    return 5;
```
Comment (EndrII) [inline src/JungleLvl/private/ground.cpp]: you need to find bug in render function of the Ground object. but not increment ground items count.
```suggestion
    return 3;
```

**Review by EndrII — CHANGES_REQUESTED** [review]

**Review by EndrII — APPROVED** [review]
